version: '3.7'
services:

    webserver:
        image:  registry.cn-beijing.aliyuncs.com/docker_wachoo_1/airflow:latest
        restart: always
#        depends_on:
#            - postgres
#            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=192.168.22.149
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_HOST=192.168.22.149
            - REDIS_PORT=6379
            - REDIS_PASSWORD=test@dbuser2020
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image:  registry.cn-beijing.aliyuncs.com/docker_wachoo_1/airflow:latest
        restart: always
#        depends_on:
#            - redis
        environment:
            - EXECUTOR=Celery
            - POSTGRES_HOST=192.168.22.149
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - REDIS_HOST=192.168.22.149
            - REDIS_PORT=6379
            - REDIS_PASSWORD=test@dbuser2020
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image:  registry.cn-beijing.aliyuncs.com/docker_wachoo_1/airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=192.168.22.149
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_HOST=192.168.22.149
            - REDIS_PORT=6379
            - REDIS_PASSWORD=test@dbuser2020
        command: scheduler

    worker:
        image:  registry.cn-beijing.aliyuncs.com/docker_wachoo_1/airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=192.168.22.149
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_HOST=192.168.22.149
            - REDIS_PORT=6379
            - REDIS_PASSWORD=test@dbuser2020
        command: worker
